'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={scheduled:'等待定时采集',queued:'等待中',running:'计算中',paused:'已暂停',completed:'已完成',partial:'部分失败',failed:'失败',success:'成功',pending:'待计算'},types={mock:'模拟数据（仅供测试）',current_estimate:'当前预计耗时（非未来预测）'},dataUseLabels={unmarked:'未标注',mock:'模拟测试',pilot:'真实试采',formal:'正式采集'};
let view='',settings={},targets=[],activeJob=null,page=1,summaryPage=1,filters={},selectedTargets=new Set(),selectedJobs=new Set(),selectedDatasets=new Set(),wizard={step:1,times:'08:00',crs:'WGS84',mode:'exact',candidates:5,date:new Date().toLocaleDateString('en-CA'),directions:['outbound'],source_point_ids:[],schedule:[],schedule_template:'',schedule_adjusted:false,schedule_window_confirmed:false,data_use:'unmarked',estimate_seconds:0.75,window_minutes:30},timer;
const DRAFT_KEY='traffic-accessibility-new-task-draft-v2';
function restoreWizardDraft(){try{const saved=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(saved&&typeof saved==='object'&&Array.isArray(saved.schedule)){wizard={...wizard,...saved};wizard.capacity=null;wizard.stats=saved.stats||null;return true}}catch(_){/* local storage can be unavailable or contain an old draft */}return false}
function persistWizardDraft(){try{const draft={...wizard};delete draft.capacity;localStorage.setItem(DRAFT_KEY,JSON.stringify(draft))}catch(_){/* a full disk/private mode must not block the workflow */}}
function clearWizardDraft(){try{localStorage.removeItem(DRAFT_KEY)}catch(_){} draftRestored=false}
let draftRestored=restoreWizardDraft();
async function api(url,method='GET',body){const opts={method};if(body instanceof FormData)opts.body=body;else if(body!==undefined){opts.headers={'Content-Type':'application/json'};opts.body=JSON.stringify(body)}const r=await fetch('/api'+url,opts);if(!r.ok){if([404,405].includes(r.status)&&['/version','/targets/convert-crs','/targets/bulk-delete','/jobs/bulk-delete','/datasets/bulk-delete'].includes(url))throw Error('后台版本与页面不一致，请退出应用后重新打开最新版');const x=await r.json().catch(()=>({detail:'服务响应异常'}));throw Error(typeof x.detail==='string'?x.detail:'输入格式或取值不正确，请检查后重试。')}return r.json()}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,7000)}
const providerName=p=>({mock:'模拟数据',amap:'高德地图',baidu:'百度地图'}[p]||p);
const isBuiltinTarget=t=>Boolean(t?.is_builtin)||String(t?.note||'').startsWith('内置城市中心代表点');
const methodHelp=()=>`<details class="method-help"><summary>计算方法与结果范围</summary><p>直线距离采用 Haversine 球面距离算法，不是道路距离。驾车距离和耗时由地图服务提供；模拟模式仅生成测试数据。</p><p>坐标转换采用近似算法，不用于高精度测绘。软件保留原始坐标、转换后的坐标和发送给地图服务的坐标。</p><p>可达数量只统计成功计算的目标；失败或未计算的目标不能视为不可达。按驾车耗时排序，与按直线距离排序不同。</p></details>`;
const btn=(s,a,extra='',cls='')=>`<button class="${cls}" data-action="${a}" ${extra}>${s}</button>`,head=(s,p,a='')=>`<div class="page-head"><div><h1>${s}</h1><p class="muted">${p}</p></div>${a}</div>`,badge=s=>`<span class="badge">${esc(states[s]||types[s]||s)}</span>`,metric=(n,s)=>`<div class="metric"><span>${s}</span><strong>${Number(n||0).toLocaleString()}</strong></div>`,fmt=(n,k=1)=>n==null?'—':(n/k).toLocaleString('zh-CN',{maximumFractionDigits:2}),opt=(v,s,selected)=>`<option value="${esc(v)}" ${String(v)===String(selected)?'selected':''}>${esc(s)}</option>`;
function updateSelectionControls(){
  const targetCount=$('#target-selected-count'),targetDelete=$('[data-action="bulk-delete-targets"]');
  if(targetCount)targetCount.textContent=selectedTargets.size;
  if(targetDelete)targetDelete.disabled=selectedTargets.size===0;
  const jobCount=$('#job-selected-count'),jobDelete=$('[data-action="bulk-delete-jobs"]');
  if(jobCount)jobCount.textContent=selectedJobs.size;
  if(jobDelete)jobDelete.disabled=selectedJobs.size===0;
  const dataCount=$('#data-selected-count'),dataDelete=$('[data-action="bulk-delete-datasets"]');
  if(dataCount)dataCount.textContent=selectedDatasets.size;
  if(dataDelete)dataDelete.disabled=selectedDatasets.size===0;
}
function jobTable(rows,selectable=false){return rows.length?`<div class="table-wrap"><table><thead><tr>${selectable?'<th>选择</th>':''}<th>任务名称</th><th>创建时间</th><th>数据用途</th><th>状态</th><th>已处理 / 总条数</th><th>成功 / 失败</th><th>操作</th></tr></thead><tbody>${rows.map(j=>{const active=['queued','running','scheduled'].includes(j.status);return `<tr>${selectable?`<td><input class="job-check" type="checkbox" data-action="toggle-job" data-id="${j.id}" aria-label="选择任务 ${esc(j.name)}" ${active?'disabled title="请先暂停任务"':''} ${selectedJobs.has(j.id)?'checked':''}></td>`:''}<td><a href="#job/${j.id}">${esc(j.name)}</a></td><td>${esc(new Date(j.created).toLocaleString())}</td><td>${esc(dataUseLabels[j.data_use||'unmarked'])}</td><td>${badge(j.status)}</td><td>${j.success+j.failed} / ${j.total}<br><progress class="progress-inline" value="${j.success+j.failed}" max="${j.total||1}"></progress></td><td>${j.success} / ${j.failed}</td><td><a href="#job/${j.id}">打开任务</a></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">还没有分析任务。导入点位后即可开始。</div>'}
async function route(){view=(location.hash.slice(1)||'home').split('/')[0];document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+view));$('#breadcrumb').textContent='工作空间 / '+({home:'首页',new:'新建分析任务',jobs:'任务中心',targets:'目标地点',data:'数据管理',usage:'地图查询记录',settings:'系统设置'}[view]||'任务详情');try{if(view==='home')await home();else if(view==='new')await renderWizard();else if(view==='jobs')await jobs();else if(view==='targets')await targetPage();else if(view==='data')await dataPage();else if(view==='usage')await usagePage();else if(view==='settings')await settingsPage();else if(view==='job'){page=1;filters={};await jobPage(location.hash.split('/')[1])}else location.hash='home'}catch(e){toast(e.message)}}
function keyGuide(){return `<section class="key-guide" aria-labelledby="key-guide-title"><h2 id="key-guide-title">开始真实采集：先申请高德 API Key</h2><ol><li><b>01 · 登录</b><p>打开高德开放平台控制台，注册或登录开发者账号。</p></li><li><b>02 · 创建应用</b><p>进入“应用管理”，点击“创建新应用”，填写应用信息。</p></li><li><b>03 · 添加 Key</b><p>在应用中点击“添加 Key”，服务平台选择 <strong>Web 服务</strong>。</p></li><li><b>04 · 配置本软件</b><p>复制 Key 到“系统设置”并保存；新建任务选择高德服务。正式采集前核对账户权限、配额并小规模试采。</p></li></ol><div class="toolbar"><a href="https://console.amap.com/" target="_blank" rel="noopener noreferrer">打开高德控制台</a><a href="https://lbs.amap.com/api/webservice/create-project-and-key" target="_blank" rel="noopener noreferrer">查看官方申请说明</a><a class="primary key-setup" href="#settings">前往系统设置</a></div><p>Key 只需填写在本机设置中，请妥善保管。${settings.has_key===null?'系统凭据库正在读取；若系统要求授权，请完成后刷新页面。':settings.has_key?'已保存 Key，仍需通过真实查询确认权限。':'尚未保存 Key；模拟模式仅用于测试流程。'}</p></section>`}
async function home(){const [d,j]=await Promise.all([api('/dashboard'),api('/jobs')]);$('#main').innerHTML=head('交通可达性分析','从坐标出发，比较不同目的地的驾车距离与时间。',btn('新建分析任务','new','','primary'))+keyGuide()+`<div class="metrics">${metric(d.jobs,'历史任务')}${metric(d.points,'导入点位（含异常）')}${metric(d.routes,'已完成结果（含模拟）')}${metric(d.calls,'地图查询次数')}</div><div class="hero"><div class="hero-copy"><h2>批量坐标，<br>清晰的可达性结果。</h2><p class="muted">导入 Excel 或 CSV，选择目标地点，后台计算并保存每一条结果。暂停之后，随时继续。</p>${btn('导入数据并开始','new','','primary')} <a class="subtle-link" href="/api/sample/xlsx">下载测试 Excel</a></div><div class="route-art" aria-label="起点与目标连接示意图"><svg viewBox="0 0 450 280" fill="none"><path d="M70 205L170 160L235 70M170 160L340 95M170 160L365 220" stroke="#002FA7" stroke-width="2"/><path d="M70 205L235 70M70 205L340 95M70 205L365 220" stroke="#002FA7" stroke-opacity=".25" stroke-dasharray="5 5"/><g fill="white" stroke="#002FA7" stroke-width="2"><circle cx="70" cy="205" r="7"/><circle cx="235" cy="70" r="5"/><circle cx="340" cy="95" r="5"/><circle cx="365" cy="220" r="5"/></g></svg><span class="caption">起点 → 目标地点 · 路线连接示意，非真实地图</span></div></div><div class="panel flush" style="margin-top:26px"><div class="panel-head"><h2>最近任务</h2><a href="#jobs">查看全部</a></div>${jobTable(j.slice(0,5))}</div>`}
async function jobs(){const rows=await api('/jobs');const available=new Set(rows.filter(j=>!['queued','running','scheduled'].includes(j.status)).map(j=>j.id));selectedJobs=new Set([...selectedJobs].filter(id=>available.has(id)));$('#main').innerHTML=head('任务中心','结果自动保存在本机，未完成的任务可以继续。',btn('新建分析任务','new','','primary'))+`<div class="selection-toolbar"><span><b id="job-selected-count">${selectedJobs.size}</b> 个任务已选择</span><div>${btn('选择全部可删除任务','select-all-jobs')} ${btn('清空选择','clear-jobs')} ${btn('删除选中任务','bulk-delete-jobs',selectedJobs.size?'':'disabled','danger')}</div></div><p class="muted batch-note">正在等待或计算的任务不能删除，请先打开任务并暂停。</p><div class="panel flush" id="job-list">${jobTable(rows,true)}</div>`}
function statsHTML(){const s=wizard.stats;return `<div class="metrics">${metric(s.total,'总数据量')}${metric(s.valid,'可计算记录')}${metric(s.invalid,'待检查记录')}${metric(s.duplicate,'重复记录（保留）')}</div>${btn('查看异常与重复记录','issues',`data-id="${wizard.dataset_id}"`)} <span class="muted">只计算有效数据；重复记录仍参与计算。</span>`}
// 2026 年最终锁定研究采集日：严格对应最终论文 Word。
// 新模板共 7 天、7 个自然时间轮、7 个方向时间切片；仅去程、每天北京时间 10:00。
const FORMAL_RESEARCH_PLAN=[
  {phase:'国庆D1',day_type:'holiday',date:'2026-10-01',times:['10:00'],directions:['outbound'],note:'国庆D1，固定10:00，仅客源地→重点村'},
  {phase:'国庆D2',day_type:'holiday',date:'2026-10-02',times:['10:00'],directions:['outbound'],note:'国庆D2，固定10:00，仅客源地→重点村'},
  {phase:'国庆D3',day_type:'holiday',date:'2026-10-03',times:['10:00'],directions:['outbound'],note:'国庆D3，固定10:00，仅客源地→重点村'},
  {phase:'普通周末1·周六',day_type:'weekend',date:'2026-10-17',times:['10:00'],directions:['outbound'],note:'普通周末1·周六，固定10:00，仅客源地→重点村'},
  {phase:'普通周末1·周日',day_type:'weekend',date:'2026-10-18',times:['10:00'],directions:['outbound'],note:'普通周末1·周日，固定10:00，仅客源地→重点村'},
  {phase:'普通周末2·周六',day_type:'weekend',date:'2026-10-24',times:['10:00'],directions:['outbound'],note:'普通周末2·周六，固定10:00，仅客源地→重点村'},
  {phase:'普通周末2·周日',day_type:'weekend',date:'2026-10-25',times:['10:00'],directions:['outbound'],note:'普通周末2·周日，固定10:00，仅客源地→重点村'}
];
function formalPlanRows(){return FORMAL_RESEARCH_PLAN.map(row=>({...row,times:[...row.times],directions:[...row.directions],window_minutes:30,notes:row.note}))}
const FORMAL_TEMPLATE_VERSION='final-2026-7day-10am-v1';
function scheduleMatchesFormal(rows){
  const expected=formalPlanRows();
  if(!Array.isArray(rows)||rows.length!==expected.length)return false;
  return rows.every((row,i)=>{const e=expected[i];return row.phase===e.phase&&row.day_type===e.day_type&&row.date===e.date&&JSON.stringify(row.times||[])===JSON.stringify(e.times)&&JSON.stringify(row.directions||[])===JSON.stringify(e.directions)})
}
function finalScopeMatches(){
  const sourceCount=Number((wizard.source_point_ids||[]).length||0);
  const fullSources=Number(wizard.stats?.valid||0);
  const targetCount=Number((wizard.target_ids||[]).length||0);
  const fullTargets=Number(targets.filter(t=>!isBuiltinTarget(t)).length||0);
  return sourceCount>0&&targetCount>0&&sourceCount===fullSources&&targetCount===fullTargets;
}
function scheduleRowsHTML(){
  const rows=wizard.schedule||[];
  if(!rows.length)return `<div class="empty schedule-empty">还没有采集日。先点击“一键填入7日最终锁定计划”，系统会生成7行可编辑的日期、时间和方向。</div>`;
  return `<div class="table-wrap schedule-table"><table><thead><tr><th>阶段</th><th>日期类型</th><th>实际日期（北京时间）</th><th>本日开始查询时间</th><th>方向</th><th>每轮窗口（分钟）</th><th>备注</th><th>操作</th></tr></thead><tbody>${rows.map((r,i)=>{const dirs=r.directions?.length?r.directions:['outbound','inbound'];const directionValue=dirs.length===2?'both':dirs[0];return `<tr data-schedule-row data-index="${i}"><td><input data-schedule="phase" value="${esc(r.phase||'自定义')}" aria-label="第${i+1}行阶段"></td><td><select data-schedule="day_type" aria-label="第${i+1}行日期类型">${[['workday','普通工作日'],['weekend','普通周末'],['holiday','法定节假日'],['custom','自定义']].map(([v,l])=>opt(v,l,r.day_type||'custom')).join('')}</select></td><td><input data-schedule="date" type="date" value="${esc(r.date||'')}" aria-label="第${i+1}行日期"></td><td><input data-schedule="times" value="${esc((r.times||[]).join(', '))}" placeholder="07:00,09:00" aria-label="第${i+1}行时间"></td><td><select data-schedule="directions" aria-label="第${i+1}行方向">${[['both','去程+返程'],['outbound','仅去程'],['inbound','仅返程']].map(([v,l])=>opt(v,l,directionValue)).join('')}</select></td><td><input data-schedule="window_minutes" type="number" min="1" max="120" value="${Number(r.window_minutes||30)}" aria-label="第${i+1}行窗口"></td><td><input data-schedule="notes" value="${esc(r.notes||'')}" aria-label="第${i+1}行备注"></td><td>${btn('删除本行','schedule-remove',`data-index="${i}"`)}</td></tr>`}).join('')}</tbody></table></div>`;
}
function readScheduleRows(){return [...document.querySelectorAll('[data-schedule-row]')].map(row=>{const get=k=>row.querySelector(`[data-schedule="${k}"]`)?.value??'';const directionValue=get('directions');return {phase:get('phase').trim()||'自定义',day_type:get('day_type')||'custom',date:get('date').trim(),times:get('times').split(/[,，\s]+/).map(x=>x.trim()).filter(Boolean),window_minutes:Number(get('window_minutes')||30),directions:directionValue==='both'?['outbound','inbound']:directionValue?[directionValue]:null,notes:get('notes').trim()}})}
function schedulePlanStats(rows){const globalDirections=(wizard.directions||['outbound','inbound']).length||2,rounds=rows.reduce((n,r)=>n+(r.times||[]).length,0),directionRounds=rows.reduce((n,r)=>n+(r.times||[]).length*(r.directions?.length||globalDirections),0),points=Number((wizard.source_point_ids||[]).length||wizard.stats?.valid||0),destinations=(wizard.target_ids||[]).length||targets.length,days=new Set(rows.map(r=>r.date).filter(Boolean)).size;return {days,rounds,directionRounds,planned:points*destinations*directionRounds,points,destinations}}
function collectionSettings(){
  const scheduled=wizard.collection_mode==='scheduled';
  const rows=wizard.schedule||[];
  const stats=schedulePlanStats(rows);
  const pointCount=Number((wizard.source_point_ids||[]).length||wizard.stats?.valid||0),destinationCount=Number((wizard.target_ids||[]).length||targets.filter(t=>!isBuiltinTarget(t)).length),directionCount=(wizard.directions||['outbound','inbound']).length||2;
  const templateVersion=wizard.schedule_template||'';
  const adjusted=Boolean(wizard.schedule_adjusted);
  return `<h2>安排路线采集</h2><p class="muted">这一页决定“什么时候开始查路线”。最终论文方案固定7个日期、每天北京时间10:00、仅去程；正式研究选择定时采集后，可一键填入最终计划。为进行真实高德测试，同一日期也可以设置多个不重叠时点。</p>${draftRestored?'<p class="notice">已恢复上次保存的计划草稿；请检查日期后再继续。</p>':''}<label>采集方式<select id="collection-mode">${opt('immediate','立即采集（默认）',wizard.collection_mode||'immediate')}${opt('scheduled','按日期和时间自动采集',wizard.collection_mode||'immediate')}</select></label><div class="notice" style="margin-top:16px"><strong>时间的含义：</strong>定时采集是在指定时间发起查询，不是查询历史或预测路况。每条路线都会保存自己的实际请求和响应时间。</div><div id="schedule-fields" ${scheduled?'':'hidden'} style="margin-top:24px"><div class="toolbar"><div><strong>2026年最终锁定研究计划：7天、7个时间轮、7个方向时间切片</strong><p class="muted">国庆D1/D2/D3与两组普通周末，均为北京时间10:00，仅客源地→重点村；完整31×94样本为20,398条计划观测。</p></div>${btn('一键填入7日最终锁定计划','apply-formal-plan','class="primary"')} ${btn('增加自定义采集日','schedule-add')} ${btn('保存当前计划草稿','save-schedule-draft')}</div>${rows.length?`<p class="muted">当前计划 ${stats.days} 个日期 · ${stats.rounds} 个自然时间轮 · ${stats.directionRounds} 个方向时间切片 · 按当前选择预计 ${stats.planned.toLocaleString()} 条路线（${pointCount} 个客源地 × ${destinationCount} 个重点村）；修改后会自动重算。</p><p class="muted">完整31×94计划：20,398条去程观测（不含重试）。${adjusted?' <strong>当前已调整方案。</strong>':''} ${templateVersion?`方案版本：${esc(templateVersion)}。`:''}</p>`:''}${scheduleRowsHTML()}<p class="muted">同一日期可添加多个时点，但相同日期的允许窗口不能重叠；相同日期和时间不能重复。Word未锁定允许采集窗口；当前每行的60分钟仅为临时参数，正式任务前必须由用户确认。窗口结束后不再开始新请求，已发出的请求允许完成。电脑需开机、联网、不休眠且应用保持运行。点击“保存当前计划草稿”后，刷新页面或稍后返回“新建分析任务”仍可继续编辑。</p><label class="check"><input type="checkbox" id="window-confirmed" ${wizard.schedule_window_confirmed?'checked':''}>我已确认本次任务的允许采集窗口（最终Word未规定具体分钟数）</label></div><div class="grid" style="margin-top:24px"><label>查询顺序<select id="query-order">${opt('randomized','每轮打乱顺序（建议）',wizard.query_order||'randomized')}${opt('original','按原始顺序',wizard.query_order||'randomized')}</select></label><label>随机种子（可选；一般留空）<input id="random-seed" type="number" min="0" max="2147483647" value="${wizard.random_seed??''}"></label></div><p class="muted"><strong>查询顺序：</strong>决定哪条路线先发起。最终方案仅有去程，不会被全局返程设置覆盖。<br><strong>随机种子：</strong>排序用的编号，不是地图数据。留空会自动生成并保存；暂停后继续会沿用原顺序。</p><section aria-labelledby="time-reference-title" style="margin-top:28px"><h3 id="time-reference-title">参考情景时间（仅作标签）</h3><p class="muted">最终方案只采10:00；以下时间不属于锁定计划，仅作方法说明。旧说明中出现的03:00 或静态路网时间、14:00、08:00、18:00和周六/周日 10:00均只是参考情景；节假日单独分析不等于把这些时点加入新版采集。</p></section>`;
}
const localTime=value=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'尚未采集';
function syncWizardProvider(savedProvider){
  if(wizard.step===1||wizard.providerDefault!==savedProvider||!wizard.provider)wizard.provider=savedProvider;
  wizard.providerDefault=savedProvider;
}

function jobPayload(){return {name:wizard.name||'采集规模预估',dataset_id:wizard.dataset_id,source_point_ids:wizard.source_point_ids||[],target_ids:wizard.target_ids||[],provider:wizard.provider||settings.provider,mode:wizard.mode,candidates:wizard.candidates,collection_mode:wizard.collection_mode||'immediate',estimate_seconds:wizard.estimate_seconds||0.75,window_minutes:wizard.window_minutes||30,directions:wizard.directions||['outbound'],study_id:wizard.study_id||'',schedule_template:wizard.schedule_template||'',schedule_adjusted:Boolean(wizard.schedule_adjusted),schedule_window_confirmed:Boolean(wizard.schedule_window_confirmed),...(wizard.collection_mode==='scheduled'?{dates:wizard.dates||[wizard.date],times:(wizard.times||'').split(/[,，\s]+/).filter(Boolean),schedule:wizard.schedule||[]}:{})}}
function capacityHTML(e,confirm=true){const estimated=e.estimated_minutes??e.planning_minutes;const window=e.target_window_minutes??e.window_minutes;return `<section class="notice"><h3>采集规模${confirm?'预估':'（创建时预估）'}</h3><p>${e.points} 个起点，${e.entrances} 个目标，${e.directions||1} 个方向。${e.natural_time_slots??e.batches} 个自然时间轮，${e.direction_time_slices??e.batches*(e.directions||1)} 个方向时间切片，共 ${e.total_routes} 条计划观测。</p>${e.planning_minutes===null?'<p>模拟模式不估计真实采集耗时与高德额度。</p>':`<p>请求启动上限：${fmt(e.configured_qps)} QPS；最大并发：${e.max_concurrency}。纯限流理论下限：${fmt(e.minimum_minutes)} 分钟 / 最长一轮；结合每次 ${e.assumed_seconds} 秒和并发后的离线模型估计：${fmt(estimated)} 分钟 / 最长一轮；单线程参考：${fmt(e.single_worker_minutes)} 分钟。以上均不含重试、准备和排队，不能视为完成保证。</p><p>当前目标窗口：${window} 分钟（仅定时采集适用）；有效吞吐模型：${fmt(e.effective_throughput_qps)} 条/秒；性能证据：${esc(e.performance_evidence||'离线模型（非真实验证）')}。</p><p>每日最多计划 ${e.daily_requests} 次请求（总计划 ${e.total_planned_requests||e.total_routes} 条），本机每日上限 ${e.local_daily_limit} 次，今日剩余 ${e.today_remaining} 次。全部路线在允许重试次数下最多 ${e.max_attempts} 次尝试；不代表真实调用量或高德账户额度。</p>`}${e.warnings.length?`<ul class="error">${e.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>${confirm?'<label class="check"><input id="capacity-ack" type="checkbox">我已了解上述风险，仍按当前方案创建任务</label>':''}`:''}<p class="muted">耗时是离线模型估计，不是完成保证；正式采集前仍需经授权的小规模真实吞吐验证。已有任务的估计为创建时快照。</p></section>`}

async function renderWizard(){settings=await api('/settings');syncWizardProvider(settings.provider);targets=await api('/targets');const step=wizard.step;const names=['导入客源地','检查客源地','确认坐标','选择重点村','安排采集','选择地图服务','检查并开始'];let c='';if(step===1){const ds=await api('/datasets');c=`<h2>导入客源地资料</h2><p class="muted">选择包含游客出发位置的 CSV 或 Excel。正式研究可直接使用“31客源单元_最终数据.csv”；系统会自动识别中文标题，例如“客源地编号”“客源地经度（GCJ-02）”“客源地纬度（GCJ-02）”，不要求你改列名。</p><div class="notice">开始前请先到 <a href="#targets">“研究地点”</a> 导入“94重点村_最终数据.csv”中的94个重点村。导入一次即可，历史任务会保存自己的地点快照。</div><div class="dropzone"><p>选择客源地文件（31个单元）</p><input type="file" id="upload" accept=".xlsx,.csv" aria-label="选择客源地文件"><p style="margin-top:18px">${btn('上传并检查客源地','upload','','primary')}</p><a href="/api/sample/xlsx">下载测试 Excel</a> · <a href="/api/sample/csv">下载测试 CSV</a><br><a href="/api/templates/source-nodes.xlsx">下载客源地模板</a> · <a href="/api/templates/source-nodes.csv">CSV 模板</a></div>${ds.some(d=>d.stats.valid)?`<div style="margin-top:24px"><label>或选择已检查的数据<select id="existing">${ds.filter(d=>d.stats.valid).map(d=>opt(d.id,d.name+' · '+d.stats.valid+' 个有效点位')).join('')}</select></label>${btn('使用这份数据','existing','style="margin-top:12px"')}</div>`:''}`}
if(step===2){const fields=[['point_id','编号（正式文件会自动识别 origin_id）'],['name','名称（正式文件会自动识别 origin_name）'],['lon','查询经度（必填；优先使用 GCJ-02）'],['lat','查询纬度（必填；优先使用 GCJ-02）'],['coordinate_system','查询坐标系（逐行填写时优先）'],['source_name','客源地名称（可选）'],['province','省（可选）'],['city','市或客源单元（可选）'],['county','县区（可选）'],['population','人口权重（可选）'],['population_year','人口年份（可选）'],['population_scope','人口统计范围（可选）'],['population_source','人口来源（可选）'],['notes','备注（可选）'],['category','地点等级或质量等级（可选）'],['quality_flag','质量标记（可选）'],['route_poi_type','导航地点类型（可选）'],['official_batch','公布批次（可选）'],['coordinate_method','坐标方法（可选）'],['ready_for_routing','是否可路由（可选）']];c=`<h2>检查客源地资料</h2><p class="muted">系统已尝试自动匹配列名。正式客源文件同时有 WGS84 和 GCJ-02 时，查询使用 GCJ-02 列，WGS84 只用于追溯；不要再次转换。人口保留原始口径，不自动填零、合并或判断人口重叠。检查不会修改原文件。</p><div class="grid">${fields.map(([k,label])=>`<label>${label}<select id="map-${k}">${opt('','不选择',wizard.mapping?.[k])}${wizard.columns.map((v,n)=>opt(n,v,wizard.mapping?.[k])).join('')}</select></label>`).join('')}</div><p style="margin-top:20px">${btn('检查数据','validate','','primary')}</p>${wizard.stats?statsHTML():''}`;}
if(step===3){const sourceRows=wizard.dataset_id?await api(`/source-nodes?dataset_id=${encodeURIComponent(wizard.dataset_id)}`):[];const selected=new Set((wizard.source_point_ids||[]).map(Number));if(!selected.size)sourceRows.forEach(p=>selected.add(Number(p.id)));c=`<h2>确认坐标并选择客源地</h2><div class="notice"><strong>请选择上传文件原本采用的坐标系</strong>，不是希望转换成的坐标系。经纬度数值本身通常无法判断坐标系，请查看数据来源或导出说明。</div><label>上传数据的坐标系<select id="crs">${['WGS84','GCJ-02','BD-09'].map(s=>opt(s,s,wizard.crs)).join('')}</select></label><div class="crs-guide" aria-label="坐标系说明"><article><h3>WGS84</h3><p>全球通用的地理坐标基准。常见于 GPS 设备、OpenStreetMap、国际地理数据及部分科研数据。</p><span>若使用刚才生成的城市坐标 Excel，请选择此项。</span></article><article><h3>GCJ-02</h3><p>中国大陆互联网地图常用坐标系，又称“火星坐标系”。高德地图、腾讯地图等通常使用此坐标系。</p><span>正式客源文件的查询坐标已是 GCJ-02，不要再次转换。</span></article><article><h3>BD-09</h3><p>百度地图使用的坐标系，在 GCJ-02 基础上进一步转换。百度地图获取或导出的坐标通常选择此项。</p><span>仅因地点位于中国大陆，不能直接认定为此项。</span></article></div><details class="method-help crs-method"><summary>为什么必须选对？</summary><p>同一地点在三种坐标系中的经纬度不同。选择错误会造成位置偏移，进而影响直线距离和驾车路线结果。</p><p>判断顺序：先看数据提供方说明；其次查看导出工具的坐标系选项；仍不确定时，应向数据提供方确认。软件会保留原始坐标，并在调用地图服务前自动转换。</p></details><div class="split" style="margin-top:24px"><h3>选择本次要查询的客源地</h3><div>${btn('全选客源地','select-all-sources')} ${btn('清空客源地','select-none-sources')}</div></div><p class="muted">默认已选全部有效客源地。试采时可以只选2个客源地，不需要重新制作或复制CSV；正式研究请选择全部31个。</p>${sourceRows.length?`<div class="source-picker table-wrap"><table><thead><tr><th>选择</th><th>编号</th><th>客源地</th><th>查询坐标</th><th>人口权重</th><th>状态</th></tr></thead><tbody>${sourceRows.map(p=>`<tr><td><input class="source-check" type="checkbox" name="source" value="${p.id}" ${selected.has(Number(p.id))?'checked':''} aria-label="选择客源地 ${esc(p.name||p.point_id)}"></td><td>${esc(p.source_id||p.point_id||'')}</td><td>${esc(p.name||p.source_name||'')}</td><td>${fmt(p.lon,1)}, ${fmt(p.lat,1)} · ${esc(p.crs||'')}</td><td>${p.population==null?'—':esc(p.population)}</td><td>${p.valid?'可查询':'不可查询'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">没有可选择的有效客源地，请返回上一步检查文件。</div>'}`;}
if(step===4){const researchTargets=targets.filter(t=>!isBuiltinTarget(t));const selected=wizard.target_ids||researchTargets.map(t=>t.id);c=`<div class="split"><h2>选择重点村</h2><div>${btn('全选','select-all')} ${btn('清空','select-none')}</div></div><p class="muted">这里是游客要到达的重点村。系统使用文件中已经确定的游客中心或导航入口坐标；不会重新搜索地点，也不会自动合并重复坐标。内置城市示例点已排除，不能混入本研究。</p>${researchTargets.length?`<div class="targets-grid">${researchTargets.map(t=>`<label class="check"><input type="checkbox" name="target" value="${t.id}" ${selected.includes(t.id)?'checked':''}>${esc(t.name)}${t.entrance_name?` · ${esc(t.entrance_name)}`:''}${t.category?`（${esc(t.category)}级）`:''}</label>`).join('')}</div>`:'<div class="empty">还没有研究重点村。请先到“目标地点”批量导入94重点村文件。</div>'}`}
if(step===5)c=collectionSettings();
if(step===6){
  const hasSchedule=Array.isArray(wizard.schedule)&&wizard.schedule.length>0;
  const hasPerDateDirections=hasSchedule&&wizard.schedule.every(row=>Array.isArray(row.directions)&&row.directions.length>0);
  const directionUnion=[...new Set((wizard.schedule||[]).flatMap(row=>row.directions||[]))];
  const directionPanel=hasPerDateDirections
    ? `<div class="notice direction-summary" style="margin-top:24px"><strong>采集方向已在上一页按日期设置</strong><p>本任务会严格按每一行的方向执行，不需要在这里重复选择。最终锁定方案仅查询去程；返程不属于新版研究计划。</p><p class="muted">当前计划方向：${directionUnion.includes('outbound')?'去程':''}${directionUnion.includes('outbound')&&directionUnion.includes('inbound')?'、':''}${directionUnion.includes('inbound')?'返程':''}。若要修改，请返回“安排采集”页面修改对应日期。</p></div>`
    : `<fieldset style="margin-top:24px"><legend>${hasSchedule?'默认采集方向（仅用于未单独设置方向的日期）':'采集方向（至少选择一个）'}</legend><label class="check"><input type="checkbox" id="direction-outbound" ${wizard.directions?.includes('outbound')?'checked':''}>去程：客源节点 → 旅游目的地</label><label class="check"><input type="checkbox" id="direction-inbound" ${wizard.directions?.includes('inbound')?'checked':''}>返程：旅游目的地 → 客源节点</label><p class="muted">${hasSchedule?'已有单独方向的日期不会受这里影响；只有未设置方向的自定义日期使用这里的默认值。':'双向会为同一客源—目的地配对分别请求两次；两条方向保留独立观测和实际请求时间。'}</p></fieldset>`;
  c=`<h2>计算方式与地图服务</h2><div class="grid"><label>模式<select id="mode">${opt('exact','全部目标（完整比较）',wizard.mode)}${opt('saving','附近目标（减少查询）',wizard.mode)}</select></label><label>每个起点选几个附近目标<input id="candidates" type="number" min="1" max="1000" value="${wizard.candidates}"></label><label>地图服务（默认采用系统设置）<select id="provider">${opt('mock','模拟数据（仅供测试）',wizard.provider||settings.provider)}${opt('amap','高德 · 当前路线估算',wizard.provider||settings.provider)}</select></label><label>预估每次请求耗时（秒，可按试采调整）<input id="estimate-seconds" type="number" min="0.01" max="300" step="0.1" value="${wizard.estimate_seconds||0.75}"></label><label>高德路线策略<select id="strategy">${[['32','高德推荐'],['36','少收费'],['37','大路优先'],['38','速度最快']].map(([v,s])=>opt(v,s,wizard.strategy||'32')).join('')}</select></label></div>${directionPanel}<div class="notice" style="margin-top:24px"><strong>“每个起点选几个附近目标”是什么意思？</strong>只在“附近目标（减少查询）”模式下生效。例如已选 31 个目标，填 5 就是为每个客源点按直线距离选最近 5 个，再查询这些配对的驾车路线；不是自动搜索 5 个新地点。未选中的配对不计入失败或不可达。</div><p class="muted">完整比较适合研究级 OD；附近目标模式用于试采或控制规模，可能遗漏驾车时间更短的目标。</p><div class="notice"><strong>地图服务说明：</strong>高德返回的是请求时的当前路线估算；计划日期和时间只用于调度和标签，不能生成历史或预测路况。模拟数据只用于测试。</div><label class="check"><input type="checkbox" id="ack" ${wizard.ack?'checked':''}>我已了解：结果为实际查询期间的路线预计耗时</label>`;
}
if(step===7){wizard.capacity=await api('/jobs/estimate','POST',jobPayload());const n=wizard.capacity.points,t=wizard.target_ids.length,k=wizard.mode==='saving'?Math.min(wizard.candidates,t):t,nt=wizard.capacity.natural_time_slots??wizard.capacity.batches,ds=wizard.capacity.direction_time_slices??wizard.capacity.batches*(wizard.capacity.directions||1);c=`<h2>确认分析任务</h2>${capacityHTML(wizard.capacity)}<label>任务名称<input id="job-name" value="${esc(wizard.name||'可达性分析 '+(wizard.collection_mode==='scheduled'?wizard.date:new Date().toLocaleDateString('en-CA')))}" maxlength="120"></label><label>数据用途<select id="data-use">${opt('unmarked','未标注（需后续明确）',wizard.data_use||'unmarked')}${opt('mock','模拟测试',wizard.data_use)}${opt('pilot','真实试采',wizard.data_use)}${opt('formal','正式采集',wizard.data_use)}</select></label><div class="equation"><span>${n.toLocaleString()}<small>有效客源地</small></span><span>×</span><span>${k}<small>每个起点的重点村数</small></span><span>×</span><span>${ds}<small>方向时间切片</small></span><span>=</span><span class="total">${wizard.capacity.total_routes.toLocaleString()}<small>条计划观测</small></span></div><p>本方案包含 ${nt} 个自然时间轮、${ds} 个方向时间切片。采集方式：${wizard.collection_mode==='scheduled'?'定时采集 · 不复用缓存 · 每行窗口按计划设置':'立即采集'}。当前采用有界并发，QPS与并发分别控制；实际查询耗时、重试和落盘仍会影响完成数量。最长一轮 ${wizard.capacity.routes_per_batch} 条路线，离线模型估计 ${fmt(wizard.capacity.estimated_minutes??wizard.capacity.planning_minutes)} 分钟（未计重试）。</p>${wizard.collection_mode==='scheduled'?`<p>计划采集：${esc((wizard.dates||[wizard.date]).join("、"))} · ${esc(wizard.times)}（北京时间）</p>`:''}<p>查询顺序：${wizard.query_order==='original'?'原始顺序':'每轮随机排序'} · 随机种子：${wizard.random_seed??'自动生成并保存'}</p><p>地图服务：${badge(providerName(wizard.provider))}　输入坐标系：${esc(wizard.crs)}</p><p class="muted">有效 ${n} 条，异常 ${wizard.stats.invalid} 条，重复 ${wizard.stats.duplicate} 条（保留）。预计 ${wizard.provider==='mock'?0:wizard.capacity.total_planned_requests} 次地图查询（不含失败后重试）。实际次数取决于失败重试和每日查询上限。</p><div class="notice">${wizard.provider==='mock'?'本任务使用模拟数据，只用于体验功能，不能作为交通研究结果。':'结果为实际采集期间的路线预计耗时。'} ${wizard.mode==='saving'?'仅统计所选的附近目标，不代表全部目标。':''}</div>`}
$('#main').innerHTML=head('新建分析任务','按步骤选择数据和计算条件。')+`<div class="steps">${names.map((n,i)=>`<div class="step ${i+1===step?'active':''}"><b>${String(i+1).padStart(2,'0')}</b>${n}</div>`).join('')}</div><div class="panel">${c}<div class="wizard-actions">${btn('上一步','wizard-back',step===1?'disabled':'')}${btn(step===7?(wizard.collection_mode==='scheduled'?'创建定时采集':'开始采集'):'下一步','wizard-next',step===1?'disabled':'','primary')}</div></div>`}
async function doValidate(){const mapping={...(wizard.mapping||{})};for(const k of ['point_id','name','lon','lat','coordinate_system','source_name','province','city','county','population','population_year','population_scope','population_source','notes','category','quality_flag','route_poi_type','official_batch','coordinate_method','ready_for_routing']){const el=$('#map-'+k);if(!el)continue;const v=el.value??'';mapping[k]=v===''?null:Number(v)}wizard.mapping=mapping;wizard.stats=await api('/imports/'+wizard.dataset_id+'/validate','POST',{mapping,crs:wizard.crs});await renderWizard()}
async function nextStep(){
  const s=wizard.step;
  if(s===2){await doValidate();if(!wizard.stats.valid)throw Error('没有可用于路线查询的有效坐标，请先修正标红行');}
  if(s===3){wizard.crs=$('#crs').value;if(!wizard.existing)wizard.stats=await api('/imports/'+wizard.dataset_id+'/validate','POST',{mapping:wizard.mapping,crs:wizard.crs});const selected=[...document.querySelectorAll('input[name=source]:checked')].map(x=>Number(x.value));if(!selected.length)throw Error('至少选择一个客源地');wizard.source_point_ids=selected;if(!wizard.stats?.valid)throw Error('当前坐标系下没有有效坐标');}
  if(s===4){wizard.target_ids=[...document.querySelectorAll('input[name=target]:checked')].map(x=>+x.value);if(!wizard.target_ids.length)throw Error('至少选择一个重点村');}
  if(s===5){
    wizard.query_order=$('#query-order').value;
    const seed=$('#random-seed').value;
    wizard.random_seed=seed===''?null:Number(seed);
    if(wizard.random_seed!==null&&(!Number.isInteger(wizard.random_seed)||wizard.random_seed<0||wizard.random_seed>2147483647))throw Error('随机种子应为 0—2147483647 的整数');
    wizard.collection_mode=$('#collection-mode').value;
    if(wizard.collection_mode==='scheduled'){
      const rows=readScheduleRows();
      if(!rows.length)throw Error('请先点击“一键填入7日最终锁定计划”，或增加至少一个采集日');
      const seenSlots=new Set(),now=Date.now();
      const normalized=rows.map((row,i)=>{
        if(!/^\d{4}-\d{2}-\d{2}$/.test(row.date)||Number.isNaN(Date.parse(row.date+'T00:00:00+08:00')))throw Error(`第${i+1}行日期无效，请选择实际日期`);
        const times=[...new Set(row.times)].sort();
        if(!times.length||!times.every(t=>/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))throw Error(`第${i+1}行时间应写成 HH:MM，例如 09:00`);
        for(const t of times){const slot=row.date+'T'+t;if(seenSlots.has(slot))throw Error(`采集时间 ${row.date} ${t} 重复，请删除重复安排`);seenSlots.add(slot);if(new Date(slot+':00+08:00').getTime()<=now)throw Error(`第${i+1}行包含已经过去的时间：${row.date} ${t}；过去时间不能补采`)}
        if(!['workday','weekend','holiday','custom'].includes(row.day_type))row.day_type='custom';
        if(!Number.isInteger(row.window_minutes)||row.window_minutes<1||row.window_minutes>120)throw Error(`第${i+1}行采集窗口应为 1—120 分钟`);
        return {...row,times,directions:row.directions?.length?[...new Set(row.directions)]:null};
      });
      // A date may intentionally have several time points (for a real-data
      // scheduler trial).  The same clock slot remains unique, and adjacent
      // windows on the same date must not overlap.  The backend repeats this
      // check when the task is created, so a draft cannot bypass it.
      const sameDate={};
      normalized.forEach((row,i)=>{for(const time of row.times){(sameDate[row.date]??=[]).push({row:i,time,window:row.window_minutes,start:new Date(`${row.date}T${time}:00+08:00`).getTime()})}});
      for(const [date,slots] of Object.entries(sameDate)){
        slots.sort((a,b)=>a.start-b.start);
        for(let k=1;k<slots.length;k++){
          const previous=slots[k-1],current=slots[k],required=Math.max(previous.window,current.window)*60000;
          if(current.start-previous.start<required)throw Error(`日期 ${date} 的采集窗口重叠：${date} ${String(previous.time)} 与 ${current.time}，请调整时点或缩短窗口`);
        }
      }
      wizard.schedule=normalized;
      wizard.dates=normalized.map(x=>x.date);
      wizard.date=wizard.dates[0];
      wizard.times=[...new Set(normalized.flatMap(x=>x.times))].sort().join(',');
      wizard.day_type=normalized[0].day_type;
      wizard.window_minutes=normalized[0].window_minutes;
      wizard.schedule_window_confirmed=Boolean($('#window-confirmed')?.checked);
      const lockedCalendar=scheduleMatchesFormal(normalized);
      wizard.schedule_template=lockedCalendar&&finalScopeMatches()?FORMAL_TEMPLATE_VERSION:'custom';
      wizard.schedule_adjusted=!lockedCalendar||!finalScopeMatches();
    }else{
      wizard.schedule=[];wizard.dates=[];wizard.times='';wizard.date='';wizard.day_type='custom';wizard.window_minutes=30;wizard.schedule_template='';wizard.schedule_adjusted=false;
    }
  }
  if(s===6){
    wizard.estimate_seconds=Number($('#estimate-seconds').value);
    if(!Number.isFinite(wizard.estimate_seconds)||wizard.estimate_seconds<0.01||wizard.estimate_seconds>300)throw Error('预估耗时须为 0.01—300 秒');
    wizard.mode=$('#mode').value;wizard.candidates=+$('#candidates').value;wizard.provider=$('#provider').value;wizard.strategy=$('#strategy').value;
    if(wizard.schedule_template===FORMAL_TEMPLATE_VERSION&&(wizard.mode!=='exact'||!finalScopeMatches())){wizard.schedule_template='custom';wizard.schedule_adjusted=true;}
    const hasSchedule=Array.isArray(wizard.schedule)&&wizard.schedule.length>0;
    const hasPerDateDirections=hasSchedule&&wizard.schedule.every(row=>Array.isArray(row.directions)&&row.directions.length>0);
    if(hasPerDateDirections){
      // The calendar is authoritative for a formal plan. Keep the task-level
      // union only for legacy fields and for capacity display; do not let the
      // second-page fallback controls overwrite a date's chosen direction.
      wizard.directions=[...new Set(wizard.schedule.flatMap(row=>row.directions))];
    }else{
      wizard.directions=[];
      if($('#direction-outbound')?.checked)wizard.directions.push('outbound');
      if($('#direction-inbound')?.checked)wizard.directions.push('inbound');
      if(!wizard.directions.length)throw Error('至少选择去程或返程一个方向');
    }
    if(wizard.schedule?.length)wizard.schedule=wizard.schedule.map(x=>({...x,directions:x.directions?.length?[...new Set(x.directions)]:wizard.directions}));
    wizard.ack=$('#ack').checked;
    if(!Number.isInteger(wizard.candidates)||wizard.candidates<1)throw Error('附近目标数量须为大于 0 的整数');
    if(wizard.provider==='amap'&&!wizard.ack)throw Error('请勾选并确认：高德返回的是查询时的当前预计耗时，不是历史或未来预测');
  }
  if(s===7){
    if(wizard.capacity?.warnings.length&&!$('#capacity-ack').checked)throw Error('请先确认采集规模风险');
    wizard.name=$('#job-name').value;
    wizard.data_use=$('#data-use').value||'unmarked';
    if(wizard.data_use==='formal'&&wizard.collection_mode==='scheduled'&&!wizard.schedule_window_confirmed)throw Error('正式采集前必须先确认允许采集窗口；最终Word没有锁定具体分钟数。');
    const payload={estimate_seconds:wizard.estimate_seconds||0.75,acknowledge_capacity:!!$('#capacity-ack')?.checked,name:wizard.name,query_order:wizard.query_order||'randomized',random_seed:wizard.random_seed??null,collection_mode:wizard.collection_mode||'immediate',window_minutes:wizard.window_minutes||30,schedule_window_confirmed:Boolean(wizard.schedule_window_confirmed),dataset_id:wizard.dataset_id,source_point_ids:wizard.source_point_ids||[],target_ids:wizard.target_ids,directions:wizard.directions||['outbound'],study_id:wizard.study_id||'',schedule_template:wizard.schedule_template||'',schedule_adjusted:Boolean(wizard.schedule_adjusted),mode:wizard.mode,candidates:wizard.candidates,provider:wizard.provider,strategy:wizard.strategy,data_use:wizard.data_use||'unmarked',acknowledge_estimate:wizard.ack||false};
    if(wizard.collection_mode==='scheduled')Object.assign(payload,{date:wizard.date,dates:wizard.dates,times:(wizard.times||'').split(/[,，\s]+/).filter(Boolean),day_type:wizard.day_type||'custom',schedule:wizard.schedule||[]});
    const j=await api('/jobs','POST',payload);clearWizardDraft();wizard.step=1;location.hash='job/'+j.id;return;
  }
  wizard.step++;persistWizardDraft();await renderWizard();
}
function progressHTML(j){const p=j.performance||{};const perf=p.attempts?`<br>请求尝试：${p.attempts}；平均接口耗时：${fmt(p.avg_provider_seconds)} 秒；平均原始响应落盘：${fmt(p.avg_raw_persistence_seconds)} 秒；平均分段保存：${fmt(p.avg_segment_persistence_seconds)} 秒；平均数据库提交：${fmt(p.avg_database_seconds)} 秒；平均持久化总耗时：${fmt(p.avg_persistence_seconds)} 秒；最大并发：${p.max_concurrency||j.config?.capacity_estimate?.max_concurrency||'—'}`:'';return `<div class="split"><div>${badge(j.status)} <span class="muted">${esc(j.message)}</span></div><div>${btn('暂停','control','data-command="pause" '+(!['running','queued','scheduled'].includes(j.status)?'disabled':''))} ${btn('继续','control','data-command="resume" '+(!['paused','failed'].includes(j.status)?'disabled':''))} ${btn('重试失败项','control','data-command="retry" '+(['running','queued','scheduled'].includes(j.status)?'disabled':''))}</div></div><p>实际采集开始（北京时间）：${esc(localTime(j.collection?.started_at))}<br>实际采集结束 / 最新响应（北京时间）：${esc(localTime(j.collection?.finished_at))}${['completed','partial','failed'].includes(j.status)?' · 本次采集已结束':''}${perf}</p><p class="muted">${j.config?.collection_mode==='scheduled'?'定时采集 · 每时段 '+j.config.window_minutes+' 分钟 · 不使用缓存；错过窗口不补采':'立即采集'}</p><div class="metrics">${metric(j.total,'总条数')}${metric(j.success,'成功')}${metric(j.failed,'失败')}${metric(j.total?Math.floor((j.success+j.failed)/j.total*100):0,'进度 %')}</div><progress max="${j.total||1}" value="${j.success+j.failed}"></progress>`}
async function jobPage(id){activeJob=await api('/jobs/'+id);const j=activeJob;$('#main').innerHTML=head(esc(j.name),'创建于 '+esc(new Date(j.created).toLocaleString()),`<div>${btn('重命名','rename')} ${btn('删除任务','delete-job')} <label style="display:inline-flex;align-items:center;gap:6px">数据用途<select id="job-data-use">${opt('unmarked','未标注',j.config.data_use||'unmarked')}${opt('mock','模拟测试',j.config.data_use)}${opt('pilot','真实试采',j.config.data_use)}${opt('formal','正式采集',j.config.data_use)}</select></label> ${btn('保存用途','save-data-use')} ${btn('导出论文分析表','export-paper','','primary')} ${btn('导出质量报告','export-quality')} ${btn('导出数据包（含原始响应）','export-package')} ${btn('导出数据包（不含原始响应）','export-package-no-raw')}</div>`)+`<div class="notice">数据用途：<strong>${esc(dataUseLabels[j.config.data_use||'unmarked'])}</strong>。${esc(types[j.config.provider]||'高德：当前路线估算，非指定时刻预测')}。${j.config.mode==='saving'?'仅比较附近目标，可能遗漏更快的路线。':'比较全部所选目标。'} 关闭标签页后仍在后台运行。</div><div class="panel" id="job-progress">${progressHTML(j)}</div><section class="panel" id="research-report"><p>正在生成采集完整性报告…</p></section><div class="panel flush"><div class="panel-head"><h2>路线明细</h2><div>${btn('查看排名与可达数量','summary')} ${btn('导出论文分析表','export-paper','','primary')} ${btn('导出质量报告','export-quality')} ${btn('导出汇总 Excel','export-summary')} ${btn('导出数据包（含原始响应）','export-package')} ${btn('导出数据包（不含原始响应）','export-package-no-raw')} ${btn('导出筛选明细','export','','primary')}</div></div><div style="padding:20px"><div class="toolbar"><input id="search" placeholder="搜索点位 ID、名称或目标" aria-label="搜索"><select id="filter-status">${opt('','全部状态')}${opt('success','成功')}${opt('failed','失败')}${opt('pending','待计算')}</select><select id="filter-target">${opt('','全部目标')}${j.config.targets.map(t=>opt(t.name,t.name)).join('')}</select><select id="filter-hours">${opt('','不限驾车时间')}${[1,2,3,4,6,8].map(h=>opt(h,'≤ '+h+' 小时')).join('')}</select><select id="filter-direction">${opt('','全部方向')}${opt('outbound','去程')}${opt('inbound','返程')}</select><select id="filter-time">${opt('','全部采集批次')}${j.config.collection_mode==='scheduled'?j.config.departures.map(t=>opt(t,t.replace('T',' ').replace('+08:00',''))).join(''):''}</select><select id="sort">${opt('id','按原始顺序')}${opt('query_order','按计划查询顺序')}${opt('requested_at','按实际请求时间')}${opt('straight_km','直线距离 ↑')}${opt('distance_meters','驾车距离 ↑')}${opt('duration_seconds','驾车时间 ↑')}</select>${btn('筛选','filter')}</div></div><div id="results"></div></div><p class="muted">请结合实际采集起止时间、成功率和缺测情况分析结果。</p>${methodHelp()}<div class="panel"><div class="split"><h2>任务记录</h2>${btn('刷新记录','logs')}</div><div id="logs"></div></div>`;await resultTable();await logTable();await showResearch();if(j.config.capacity_estimate)$('#job-progress').insertAdjacentHTML('afterend',capacityHTML(j.config.capacity_estimate,false))}
let reportBusy=false,lastReportRefresh=0;
function reportTable(headers,rows){return `<div class="table-wrap report-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x??'—')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">暂无可比较数据</td></tr>`}</tbody></table></div>`}
async function showResearch(){if(reportBusy||!activeJob)return;reportBusy=true;const id=activeJob.id;try{const r=await api('/jobs/'+id+'/research');if(activeJob?.id!==id||!$('#research-report'))return;lastReportRefresh=Date.now();const expanded=[...$('#research-report').querySelectorAll('details')].map(d=>d.open);$('#research-report').innerHTML=`<div class="split"><h2>采集完整性与多日比较</h2><div>${btn('刷新报告','research-refresh')} ${btn('导出报告 Excel','research-export')}</div></div><p>${r.provider==='mock'?'模拟测试报告 · 不用于实际交通研究':'高德实际采集报告'} · 生成于 ${esc(localTime(r.generated_at))}</p><p class="muted">计划模板：${esc(r.schedule_template||'自定义/旧任务')} ${r.schedule_adjusted?'· 已调整方案':''} · 查询顺序：${r.query_order==='randomized'?'每批随机排序':'原始顺序'} · 随机种子：${r.random_seed??'—'} · 算法：${esc(r.order_algorithm)} · 采集窗口确认：${r.schedule_window_confirmed?'是':'待确认'}</p><h3>各日期 / 时段完整性</h3>${reportTable(['计划批次','研究阶段','状态','应采','成功','失败','待采','错过窗口','错过窗口原因','有效成功','双向配对适用','双向均成功','完整率 %','实际开始','实际结束','响应跨窗口','路况路线','平均路况覆盖率 %'],r.windows.map(w=>[r.collection_mode==='immediate'?'立即采集':w.departure.replace('T',' '),w.phase||'—',w.state,w.expected,w.success,w.failed,w.pending,w.missed,JSON.stringify(w.window_miss_reasons||{}),w.eligible,w.bidirectional_applicable?'是':'不适用',w.bidirectional_applicable?w.bidirectional_pairs:'不适用',w.completeness_pct,localTime(w.started),localTime(w.finished),w.response_crossed,w.traffic_routes,w.traffic_coverage==null?'—':fmt(w.traffic_coverage)]))}<h3>按方向完整性</h3>${reportTable(['计划批次','研究阶段','方向','应采','成功','失败','待采','有效成功','完整率 %','已发起','请求尝试','响应跨窗口'],(r.direction_windows||[]).map(w=>[w.departure.replace('T',' '),w.phase||'—',w.direction==='inbound'?'返程':'去程',w.expected,w.success,w.failed,w.pending,w.eligible,w.completeness_pct,w.requested,w.attempts,w.response_crossed]))}<details class="method-help"><summary>多日统计与时段比较</summary><p>仅比较已结束批次；使用所有这些批次共同有效的起终点对。缺测可能缩小共同样本，零共同样本不计算结果。单位：分钟。</p>${reportTable(['时段','日期类型','已结束日期','有效日期','共同起终点对','日均耗时均值','日均耗时中位数','日均耗时标准差'],r.statistics.map(x=>[x.time,x.day_type,x.closed_days,x.valid_days,x.common_od,fmt(x.mean),fmt(x.median),fmt(x.sd)]))}<h3>相同日期的时段配对比较</h3><p>差值为后时段减前时段；正值表示后时段耗时更长。仅为描述统计，不代表统计显著性。</p>${reportTable(['前时段','后时段','配对日期','共同起终点对','平均差','差值中位数','差值标准差'],r.paired.map(x=>[x.first,x.second,x.paired_days,x.common_od,fmt(x.mean),fmt(x.median),fmt(x.sd)]))}</details><details class="method-help"><summary>报告计算口径</summary><p>${esc(r.method)}</p><p>同一任务内使用同一目标快照、地图服务和路线策略。日期类型需人工确认；不同任务未自动合并。报告会随采集更新，导出的文件保存导出时的快照。</p></details>`;$('#research-report').querySelectorAll('details').forEach((d,i)=>d.open=expanded[i]||false)}finally{reportBusy=false}}
function query(){return new URLSearchParams({...filters,page,size:50}).toString()}
async function resultTable(){const r=await api(`/jobs/${activeJob.id}/results?${query()}`);$('#results').innerHTML=r.rows.length?`<div class="table-wrap"><table><thead><tr><th>方向</th><th>点位 ID / 名称</th><th>原始经纬度 / 坐标系</th><th>目标 / 经纬度</th><th>直线距离（km）</th><th>驾车距离（km）</th><th>预计耗时（分钟）</th>${activeJob.config.collection_mode==='scheduled'?'<th>计划时间（北京时间）</th>':''}<th>实际请求时间（北京时间）</th><th>数据类型</th><th>状态</th><th>详情</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${x.direction==='inbound'?'返程':'去程'}</td><td>${esc(x.point_id)}<br>${esc(x.point_name)}</td><td>${x.origin_lon}, ${x.origin_lat}<br>${esc(x.origin_crs)}</td><td>${esc(x.target_name)}<br>${x.target_lon}, ${x.target_lat}</td><td>${fmt(x.straight_km)}</td><td>${fmt(x.distance_meters,1000)}</td><td>${fmt(x.duration_seconds,60)}</td>${activeJob.config.collection_mode==='scheduled'?`<td>${esc(x.departure.replace('T',' ').replace('+08:00',''))}</td>`:''}<td>${x.requested_at?esc(new Date(x.requested_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})):'—'}</td><td>${esc(types[x.traffic_type]||'—')}<br>${esc(providerName(x.provider))}${x.cache_hit?' · 复用已有结果':''}</td><td>${badge(x.status)}</td><td title="${esc(x.request_coords)}">${esc(x.error||x.fetched_at||x.calculated_at||'—')}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>共 ${r.total.toLocaleString()} 条 · 第 ${page} / ${Math.ceil(r.total/50)} 页</span><div>${btn('上一页','prev',page===1?'disabled':'')} ${btn('下一页','next',page*50>=r.total?'disabled':'')}</div></div>`:'<div class="empty">暂无符合条件的结果。任务准备中时请稍后点击「筛选」刷新。</div>'}
async function logTable(){const rows=await api('/events?job_id='+activeJob.id);$('#logs').innerHTML=rows.map(x=>`<p class="muted">${esc(x.created)}　${esc(x.message)}</p>`).join('')||'<p class="muted">暂无记录</p>'}
async function dataPage(){const rows=await api('/datasets');const available=new Set(rows.filter(d=>!d.job_count).map(d=>d.id));selectedDatasets=new Set([...selectedDatasets].filter(id=>available.has(id)));$('#main').innerHTML=head('数据管理','原始导入文件与待检查记录均保留在本机。',btn('导入数据','new','','primary'))+`<div class="selection-toolbar"><span><b id="data-selected-count">${selectedDatasets.size}</b> 份数据已选择</span><div>${btn('选择全部可删除数据','select-all-datasets')} ${btn('清空选择','clear-datasets')} ${btn('删除选中数据','bulk-delete-datasets',selectedDatasets.size?'':'disabled','danger')}</div></div><p class="muted batch-note">任务正在使用的数据不能删除。请先删除相关任务，再删除数据。</p><div class="panel flush"><div class="table-wrap"><table><thead><tr><th>选择</th><th>文件名</th><th>坐标系</th><th>总量</th><th>有效</th><th>异常</th><th>重复</th><th>使用情况</th><th>操作</th></tr></thead><tbody>${rows.map(d=>`<tr><td><input class="dataset-check" type="checkbox" data-action="toggle-dataset" data-id="${d.id}" aria-label="选择数据 ${esc(d.name)}" ${d.job_count?'disabled title="有任务正在使用"':''} ${selectedDatasets.has(d.id)?'checked':''}></td><td>${esc(d.name)}</td><td>${esc(d.crs||'待确认')}</td><td>${d.stats.total??'—'}</td><td>${d.stats.valid??'—'}</td><td>${d.stats.invalid??'—'}</td><td>${d.stats.duplicate??'—'}</td><td>${d.job_count?`${d.job_count} 个任务使用`:'可删除'}</td><td>${btn('查看异常','issues',`data-id="${d.id}"`,'small')} ${btn('批量添加为目标','as-targets',`data-id="${d.id}"`,'small')}</td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<div class="empty">尚未导入数据</div>'}</div>`}
async function targetPage(){targets=await api('/targets');const available=new Set(targets.map(t=>t.id));selectedTargets=new Set([...selectedTargets].filter(id=>available.has(id)));const researchTargets=targets.filter(t=>!isBuiltinTarget(t));if(wizard.target_ids)wizard.target_ids=wizard.target_ids.filter(id=>researchTargets.some(t=>t.id===id));const counts=targets.reduce((a,t)=>(a[t.crs]=(a[t.crs]||0)+1,a),{});$('#main').innerHTML=head('研究地点',`${researchTargets.length} 个研究重点村${targets.length-researchTargets.length?` · ${targets.length-researchTargets.length} 个内置示例点已隔离`:''} · 修改地点不会改变已有任务结果。`,`<div>${btn('批量导入重点村','target-import-open','','primary')} ${btn('新增地点','target-new')}</div>`)+`<div class="selection-toolbar target-convert"><span>当前坐标系：${Object.entries(counts).map(([crs,n])=>`${crs} ${n} 个`).join('，')||'暂无地点'}</span><div><select id="target-crs-convert" aria-label="转换后的坐标系"><option value="">选择转换后的坐标系</option>${['WGS84','GCJ-02','BD-09'].map(c=>opt(c,c)).join('')}</select> ${btn('转换全部目标地点','convert-target-crs',targets.length?'':'disabled','primary')}</div></div><p class="muted batch-note">正式研究请导入“94重点村_最终数据.csv”，文件中的中文标题会自动识别。内置城市示例点只用于演示，创建研究任务时不会自动选入。</p><div class="notice">重点村使用文件中已确定的游客中心或导航入口坐标；原始字段保留在数据管理中。批量导入后先检查数量和坐标系，再创建任务。</div><div class="selection-toolbar"><span><b id="target-selected-count">${selectedTargets.size}</b> 个地点已选择</span><div>${btn('全选可删除地点','select-all-targets',targets.length?'':'disabled')} ${btn('清空选择','clear-targets')} ${btn('删除选中地点','bulk-delete-targets',selectedTargets.size?'':'disabled','danger')}</div></div><p class="muted batch-note">删除后无法撤销。仅从地点列表移除，不删除导入数据，不影响历史任务保存的地点快照。</p><div class="panel flush"><div class="table-wrap"><table><thead><tr><th>选择</th><th>名称</th><th>经度</th><th>纬度</th><th>坐标系</th><th>等级</th><th>导航入口</th><th>备注</th><th>操作</th></tr></thead><tbody>${targets.map(t=>`<tr class="${isBuiltinTarget(t)?'builtin-row':''}"><td><input class="target-check" type="checkbox" data-action="toggle-target" data-id="${t.id}" aria-label="选择地点 ${esc(t.name)}" ${selectedTargets.has(t.id)?'checked':''}></td><td>${esc(t.name)}${isBuiltinTarget(t)?'（内置示例）':''}</td><td>${t.lon}</td><td>${t.lat}</td><td>${esc(t.crs)}</td><td>${esc(t.category||'—')}</td><td>${esc(t.entrance_name||'—')}</td><td style="max-width:360px;white-space:normal">${esc(t.note||'')}</td><td>${btn('编辑','target-edit',`data-id="${t.id}"`,'small')} ${btn('删除','target-delete',`data-id="${t.id}"`,'small')}</td></tr>`).join('')}</tbody></table></div></div>`}
let targetImport=null;
function showTargetImport(){
 const d=targetImport;
 let body='<h2>批量导入目标地点</h2>';
 if(!d)body+=`<p>支持 Excel（.xlsx）或 CSV，最大 100 MB。第一行是表头；Excel 读取当前活动工作表，请将点位表设为活动表后保存。</p><p class="muted">建议包含名称、经度、纬度列。同一文件应使用同一种坐标系。文件上传后保留在“数据管理”中。<br><a href="/api/templates/destinations.xlsx">下载旅游目的地模板</a> · <a href="/api/templates/destinations.csv">CSV 模板</a></p><label>选择文件<input id="target-import-file" type="file" accept=".xlsx,.csv"></label>${btn('上传并选择数据列','target-import-upload','style="margin-top:20px"','primary')}`;
 else if(!d.stats)body+=`<p>${esc(d.name)}</p><p class="muted">正式文件“94重点村_最终数据.csv”会自动识别中文标题，例如“重点村编号”“最终路线经度（GCJ-02）”“最终路线纬度（GCJ-02）”“路线查询坐标系”；GCJ-02坐标直接用于高德查询，不要再次转换。原始字段会完整保留。</p><div class="grid">${[['point_id','编号（可选）'],['name','名称（可选）'],['lon','查询经度（优先最终导航坐标）'],['lat','查询纬度（优先最终导航坐标）'],['coordinate_system','坐标系（逐行填写时优先）'],['province','省（可选）'],['city','市（可选）'],['county','县区（可选）'],['village_name','村名（可选）'],['entrance_name','导航入口名称（可选）'],['coordinate_source','坐标来源（可选）'],['verification_status','是否可路由（可选）'],['category','地点等级 A/B/C（可选）'],['route_poi_type','导航地点类型（可选）'],['official_batch','公布批次（可选）'],['notes','备注或核验说明（可选）']].map(([key,label])=>`<label>${label}<select id="ti-${key}">${opt('','请选择',d.mapping[key]??'')}${d.columns.map((name,i)=>opt(i,name,d.mapping[key])).join('')}</select></label>`).join('')}<label>文件坐标系<select id="ti-crs">${opt('','请选择坐标系',d.crs||'')}${['WGS84','GCJ-02','BD-09'].map(c=>opt(c,c,d.crs)).join('')}</select></label></div><p class="muted">名称为空时使用编号；编号也为空时使用文件行号。若填写“坐标系”列，逐行值优先；空白行使用上面的文件坐标系。A/B/C只记录地点质量，不会进行机构分类或自动去重。</p>${btn('检查数据','target-import-check','','primary')}`;
 else body+=`<p>${esc(d.name)} · ${esc(d.crs)}</p><div class="notice">共 ${d.stats.total} 行，可导入 ${d.stats.valid} 行，坐标异常 ${d.stats.invalid} 行，含重复标记 ${d.stats.duplicate} 行。</div><p>仅添加有效坐标记录，异常行跳过。重复记录保留，不与已有目标自动去重；不会覆盖已有目标或改变已有任务。</p>${d.issues?.length?`<details><summary>查看异常或重复记录（前 20 条）</summary><ul>${d.issues.map(r=>`<li>第 ${r.row_no} 行：${esc(JSON.parse(r.issues).join('、'))}</li>`).join('')}</ul></details>`:''}<div class="toolbar" style="margin-top:20px">${btn('返回修改数据列','target-import-back')} ${btn('确认导入 '+d.stats.valid+' 个目标','target-import-commit',d.stats.valid?'':'disabled','primary')}</div>`;
 $('#modal-body').innerHTML=body;if(!$('#modal').open)$('#modal').showModal();
}
function targetForm(t={}){$('#modal-body').innerHTML=`<h2>${t.id?'编辑':'新增'}目标地点</h2><p class="muted">可填写游客中心、景区入口等实际到达位置；不要把村委会坐标当作唯一入口。坐标系请按数据来源选择。</p><p id="target-error" class="error" role="alert" hidden></p><div class="form-stack"><label>目标名称<input id="t-name" value="${esc(t.name||'')}"></label><label>稳定目标 ID（可选）<input id="t-target-id" value="${esc(t.target_id||'')}"></label><div class="grid"><label>经度<input id="t-lon" type="number" step="any" min="-180" max="180" required placeholder="例如：114.240124" value="${t.lon??''}"></label><label>纬度<input id="t-lat" type="number" step="any" min="-90" max="90" required placeholder="例如：30.636285" value="${t.lat??''}"></label></div><label>坐标系<select id="t-crs">${['WGS84','GCJ-02','BD-09'].map(c=>opt(c,c,t.crs||'GCJ-02')).join('')}</select></label><div class="grid"><label>省<input id="t-province" value="${esc(t.province||'')}"></label><label>市<input id="t-city" value="${esc(t.city||'')}"></label><label>县区<input id="t-county" value="${esc(t.county||'')}"></label><label>村名<input id="t-village" value="${esc(t.village_name||'')}"></label></div><div class="grid"><label>入口名称<input id="t-entrance" value="${esc(t.entrance_name||'')}"></label><label>坐标来源<input id="t-coordinate-source" value="${esc(t.coordinate_source||'')}"></label><label>核验状态<input id="t-verification" value="${esc(t.verification_status||'')}"></label></div><label>备注<input id="t-note" value="${esc(t.note||'')}"></label>${btn('保存目标','target-save','data-id="'+(t.id||'')+'"','primary')}</div>`;$('#modal').showModal()}
async function settingsPage(){settings=await api('/settings');$('#main').innerHTML=head('系统设置','选择地图服务，并设置查询次数上限。')+`<div class="panel"><h2>地图服务</h2><div class="form-stack"><div class="grid"><label>默认地图服务<select id="s-provider">${opt('mock','模拟数据（仅供测试）',settings.provider)}${opt('amap','高德驾车路线',settings.provider)}</select></label><label>高德密钥（Web 服务 API Key）<input type="password" id="s-key" autocomplete="new-password" placeholder="${settings.has_key===null?'系统凭据库正在读取':settings.has_key?'已保存；留空表示不修改':'尚未配置'}"></label></div><label class="check"><input id="s-plain" type="checkbox">将新密钥保存在本机未加密文件中（仅在系统安全存储不可用时选择）</label><p class="muted">默认使用系统安全存储保存密钥。若选择未加密文件，密钥保护取决于本机文件权限，请勿共享该文件。</p><div class="grid"><label>每秒最多查询次数<input id="s-qps" type="number" min="0.1" max="20" step="0.1" value="${settings.qps}"></label><label>最大并发请求数<input id="s-concurrency" type="number" min="1" max="8" step="1" value="${settings.max_concurrency||3}"></label><label>每天最多查询次数（含重试）<input id="s-limit" type="number" min="1" value="${settings.daily_limit}"></label><label>最大自动重试次数<input id="s-retries" type="number" min="0" max="5" value="${settings.retries}"></label></div><div class="notice">请求启动QPS与并发数分别控制；每次请求都会保留尝试记录和原始响应索引。失败后会等待再试，达到每日上限后暂停。这里的上限仅约束本软件；账户剩余额度和费用请查看高德平台。</div><div>${btn('保存设置','save-settings','','primary')}</div></div></div><div class="panel"><h2>本地存储</h2><p>数据目录：<code>${esc(settings.data_dir)}</code></p><p class="muted">密钥保存方式：${esc(settings.key_storage)}。备份前先退出应用，再复制整个数据文件夹。系统安全存储中的密钥需另行配置。</p><p class="muted">研究任务默认不复用历史路线缓存；每个批次都会重新请求。历史结果只在原任务中查看，修改设置不会改变历史数据来源。</p></div>`}
async function usagePage(){const rows=await api('/usage');$('#main').innerHTML=head('地图查询记录','统计本软件发起的地图查询，包括失败和重试。模拟计算不计入。')+`<div class="panel flush"><div class="table-wrap"><table><thead><tr><th>日期 · 北京时间</th><th>地图服务</th><th>查询次数</th><th>错误次数</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.day)}</td><td>${esc(providerName(r.provider))}</td><td>${r.calls}</td><td>${r.errors}</td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<div class="empty">尚未查询地图。可以先用模拟模式体验功能。</div>'}</div>`}
async function exportFile(kind,includeRaw=true){toast(kind==='package'?(includeRaw?'正在生成含原始响应的研究数据包…':'正在生成不含原始响应的研究数据包…'):(kind==='paper'?'正在生成论文分析表…':kind==='quality'?'正在生成采集质量报告…':'正在生成 Excel…'));const params={...filters,kind};if(kind==='package')params.include_raw=String(includeRaw);const r=await fetch(`/api/jobs/${activeJob.id}/export?${new URLSearchParams(params)}`);if(!r.ok)throw Error((await r.json()).detail);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;const cd=r.headers.get('content-disposition')||'',match=cd.match(/filename\*=UTF-8''([^;]+)/i);a.download=match?decodeURIComponent(match[1]):`交通可达性_${kind}.${kind==='package'?'zip':'xlsx'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast(kind==='package'?(includeRaw?'含原始响应的研究数据包已生成，开始下载':'不含原始响应的研究数据包已生成，开始下载'):kind==='paper'?'论文分析表已生成，开始下载':kind==='quality'?'采集质量报告已生成，开始下载':'Excel 已生成，开始下载')}
async function showSummary(){const dep=filters.departure||activeJob.config.departures[0],top=Number($('#summary-top')?.value||3);const rows=await api(`/jobs/${activeJob.id}/summary?${new URLSearchParams({departure:dep,top,page:summaryPage,od_direction:filters.od_direction||''})}`);$('#modal-body').innerHTML=`<h2>起点汇总${activeJob.config.collection_mode==='scheduled'?' · '+esc(dep):''}</h2><p class="muted">${activeJob.config.institution_summary?'按机构 ID 去重，使用成功入口的最短耗时；旧任务仍按原口径。':''} ${activeJob.config.mode==='saving'?'仅附近目标预筛选':'本任务所选目标'} · ${esc(types[activeJob.config.provider]||'高德当前路线估算')} · 仅统计成功结果；去程和返程分开统计 · 第 ${summaryPage} 页</p><div class="toolbar"><select id="summary-top">${[1,3,5,10].map(n=>opt(n,'显示前 '+n+' 名',top)).join('')}</select>${btn('更新排名','summary-update')}</div><div class="table-wrap"><table><thead><tr><th>方向</th><th>点位</th><th>直线距离最近</th><th>驾车时间排名</th><th>成功路线数</th><th>不同重点村数</th><th>1 / 2 / 3 / 4 小时内成功重点村数</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.direction==='inbound'?'返程':s.direction==='outbound'?'去程':'未区分'}</td><td>${esc(s.point_id)}<br>${esc(s.point_name)}</td><td>${esc(s.nearest_straight)}</td><td>${s.top.map(t=>`${esc(t.target_name)} · ${fmt(t.duration_seconds,60)} min`).join('<br>')||'—'}</td><td>${s.success_routes}</td><td>${s.distinct_targets}</td><td>${s.reachable['1']} / ${s.reachable['2']} / ${s.reachable['3']} / ${s.reachable['4']}</td></tr>`).join('')}</tbody></table></div><div class="toolbar" style="margin-top:16px">${btn('上一页','summary-prev',summaryPage===1?'disabled':'')} ${btn('下一页','summary-next',rows.length<50?'disabled':'')}</div>`;if(!$('#modal').open)$('#modal').showModal()}
const actions={
 'toggle-job':el=>{el.checked?selectedJobs.add(el.dataset.id):selectedJobs.delete(el.dataset.id);updateSelectionControls()},
 'select-all-jobs':()=>{document.querySelectorAll('.job-check:not(:disabled)').forEach(el=>{el.checked=true;selectedJobs.add(el.dataset.id)});updateSelectionControls()},
 'clear-jobs':()=>{selectedJobs.clear();document.querySelectorAll('.job-check').forEach(el=>el.checked=false);updateSelectionControls()},
 'bulk-delete-jobs':async()=>{if(!selectedJobs.size)throw Error('请先选择要删除的任务');if(confirm(`确定删除选中的 ${selectedJobs.size} 个任务及其计算结果吗？此操作无法撤销。`)){const r=await api('/jobs/bulk-delete','POST',{ids:[...selectedJobs]});selectedJobs.clear();await jobs();toast(`已删除 ${r.deleted} 个任务`)}},
 'toggle-dataset':el=>{el.checked?selectedDatasets.add(el.dataset.id):selectedDatasets.delete(el.dataset.id);updateSelectionControls()},
 'select-all-datasets':()=>{document.querySelectorAll('.dataset-check:not(:disabled)').forEach(el=>{el.checked=true;selectedDatasets.add(el.dataset.id)});updateSelectionControls()},
 'clear-datasets':()=>{selectedDatasets.clear();document.querySelectorAll('.dataset-check').forEach(el=>el.checked=false);updateSelectionControls()},
 'bulk-delete-datasets':async()=>{if(!selectedDatasets.size)throw Error('请先选择要删除的数据');if(confirm(`确定删除选中的 ${selectedDatasets.size} 份数据及其原始文件吗？此操作无法撤销。`)){const r=await api('/datasets/bulk-delete','POST',{ids:[...selectedDatasets]});selectedDatasets.clear();await dataPage();toast(r.message)}},
 'toggle-target':el=>{const id=Number(el.dataset.id);el.checked?selectedTargets.add(id):selectedTargets.delete(id);updateSelectionControls()},
 'select-all-targets':()=>{document.querySelectorAll('.target-check').forEach(el=>{el.checked=true;selectedTargets.add(Number(el.dataset.id))});updateSelectionControls()},
 'clear-targets':()=>{selectedTargets.clear();document.querySelectorAll('.target-check').forEach(el=>el.checked=false);updateSelectionControls()},
 'bulk-delete-targets':async el=>{if(!selectedTargets.size)throw Error('请先选择要删除的目标');if(!confirm(`确定删除选中的 ${selectedTargets.size} 个目标吗？删除后无法撤销。已有任务与导入数据不受影响。`))return;el.disabled=true;try{const r=await api('/targets/bulk-delete','POST',{ids:[...selectedTargets]});selectedTargets.clear();await targetPage();toast(`已删除 ${r.deleted} 个目标`)}finally{updateSelectionControls()}},
 'convert-target-crs':async()=>{const crs=$('#target-crs-convert').value;if(!crs)throw Error('请先选择转换后的坐标系');if(confirm(`将全部 ${targets.length} 个目标转换为 ${crs} 吗？系统会换算经纬度，已有任务不受影响。`)){const r=await api('/targets/convert-crs','POST',{crs});await targetPage();toast(`已将 ${r.converted} 个目标转换为 ${crs}；${r.unchanged} 个无需转换`) }},
 'new':async()=>{clearWizardDraft();wizard={step:1,times:'08:00',crs:'WGS84',mode:'exact',candidates:5,date:'',directions:['outbound'],source_point_ids:[],schedule:[],collection_mode:'immediate',schedule_template:'',schedule_adjusted:false,schedule_window_confirmed:false,data_use:'unmarked',estimate_seconds:0.75,window_minutes:30};location.hash='new';if(view==='new')await renderWizard()},
 'upload':async()=>{const file=$('#upload').files[0];if(!file)throw Error('请选择文件');const data=new FormData();data.append('file',file);const r=await api('/imports','POST',data);Object.assign(wizard,{dataset_id:r.id,columns:r.columns,mapping:r.mapping,stats:null,step:2,existing:false});if(r.mapping?.coordinate_system!==null&&r.mapping?.coordinate_system!==undefined)wizard.crs=r.crs||'GCJ-02';await renderWizard()},
'existing':async()=>{const ds=(await api('/datasets')).find(d=>d.id===$('#existing').value);wizard.dataset_id=ds.id;wizard.stats=ds.stats;wizard.crs=ds.crs;wizard.source_point_ids=[];wizard.step=3;wizard.existing=true;await renderWizard()},
'research-refresh':showResearch,'research-export':()=>exportFile('research'),
'validate':doValidate,'wizard-next':nextStep,'wizard-back':async()=>{wizard.step=wizard.existing&&(wizard.step===3||wizard.step===4)?1:wizard.step-1;await renderWizard()},
 'apply-formal-plan':async()=>{if((wizard.schedule||[]).length&&!confirm('重新填入7日最终锁定计划会覆盖当前采集草稿，是否继续？'))return;wizard.collection_mode='scheduled';wizard.schedule=formalPlanRows();wizard.schedule_template=FORMAL_TEMPLATE_VERSION;wizard.schedule_adjusted=false;wizard.schedule_window_confirmed=false;persistWizardDraft();await renderWizard()},
 'save-schedule-draft':async()=>{const rows=readScheduleRows();if(rows.length){wizard.schedule=rows;wizard.collection_mode='scheduled';wizard.schedule_window_confirmed=Boolean($('#window-confirmed')?.checked);const lockedCalendar=scheduleMatchesFormal(rows);wizard.schedule_template=lockedCalendar&&finalScopeMatches()?FORMAL_TEMPLATE_VERSION:'custom';wizard.schedule_adjusted=!lockedCalendar||!finalScopeMatches();persistWizardDraft();toast('采集计划草稿已保存；刷新页面后仍可继续编辑')}else throw Error('请先填入至少一个采集日')},
 'schedule-add':async()=>{const rows=readScheduleRows();wizard.schedule=[...rows,{phase:'自定义',day_type:'custom',date:'',times:['08:00'],window_minutes:30,directions:null,notes:''}];wizard.collection_mode='scheduled';persistWizardDraft();await renderWizard()},
 'schedule-remove':async el=>{const rows=readScheduleRows();const index=Number(el.dataset.index);if(rows.length<=1)throw Error('至少保留一个采集日；如不需要定时采集，请切换为立即采集');wizard.schedule=rows.filter((_,i)=>i!==index);persistWizardDraft();await renderWizard()},
'select-all':()=>document.querySelectorAll('input[name=target]').forEach(x=>x.checked=true),'select-none':()=>document.querySelectorAll('input[name=target]').forEach(x=>x.checked=false),
'select-all-sources':()=>document.querySelectorAll('input[name=source]').forEach(x=>x.checked=true),'select-none-sources':()=>document.querySelectorAll('input[name=source]').forEach(x=>x.checked=false),
'issues':async el=>{const r=await api(`/datasets/${el.dataset.id}/points?issues=true&size=200`);$('#modal-body').innerHTML=`<h2>异常与重复记录</h2><p class="muted">共 ${r.total} 条，显示前 200 条。原始数据保留，不自动删除。</p><div class="table-wrap"><table><thead><tr><th>行号</th><th>ID</th><th>名称</th><th>问题</th><th>原始行</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td>${p.row_no}</td><td>${esc(p.point_id)}</td><td>${esc(p.name)}</td><td>${esc(JSON.parse(p.issues).join('、'))}</td><td>${esc(p.raw)}</td></tr>`).join('')}</tbody></table></div>`;$('#modal').showModal()},
'control':async el=>{await api(`/jobs/${activeJob.id}/${el.dataset.command}`,'POST');activeJob=await api('/jobs/'+activeJob.id);$('#job-progress').innerHTML=progressHTML(activeJob);await resultTable()},
'rename':async()=>{const name=prompt('任务名称',activeJob.name);if(name){await api('/jobs/'+activeJob.id,'PATCH',{name});await jobPage(activeJob.id)}},
'save-data-use':async()=>{const value=$('#job-data-use').value;await api('/jobs/'+activeJob.id,'PATCH',{name:activeJob.name,data_use:value});activeJob=await api('/jobs/'+activeJob.id);await jobPage(activeJob.id);toast('数据用途已保存；历史观测内容未改变')},
'delete-job':async()=>{if(confirm('删除任务及其结果？原始数据和可复用结果会保留。')){await api('/jobs/'+activeJob.id,'DELETE');location.hash='jobs'}},
'filter':async()=>{filters={q:$('#search').value,status:$('#filter-status').value,target:$('#filter-target').value,departure:$('#filter-time').value,od_direction:$('#filter-direction').value,sort:$('#sort').value};if($('#filter-hours').value)filters.hours=$('#filter-hours').value;page=1;await resultTable()},
'prev':async()=>{page--;await resultTable()},'next':async()=>{page++;await resultTable()},'logs':logTable,'export':()=>exportFile('details'),'export-paper':()=>exportFile('paper'),'export-quality':()=>exportFile('quality'),'export-summary':()=>exportFile('summary'),'export-package':()=>exportFile('package',true),'export-package-no-raw':()=>exportFile('package',false),
'summary':async()=>{summaryPage=1;await showSummary()},'summary-update':showSummary,'summary-prev':async()=>{summaryPage--;await showSummary()},'summary-next':async()=>{summaryPage++;await showSummary()},
'as-targets':async el=>{if(confirm('全部可计算记录添加为目标？重复记录也保留。')){await api(`/datasets/${el.dataset.id}/as-targets`,'POST');toast('目标已批量添加')}},
 'target-import-open':()=>{targetImport=null;showTargetImport()},
 'target-import-upload':async el=>{const file=$('#target-import-file').files[0];if(!file)throw Error('请先选择 Excel 或 CSV 文件');el.disabled=true;try{const form=new FormData();form.append('file',file);const r=await api('/imports','POST',form);targetImport={...r,name:file.name,crs:r.crs||''};showTargetImport()}finally{el.disabled=false}},
 'target-import-check':async el=>{const d=targetImport;d.crs=$('#ti-crs').value;if(!d.crs)throw Error('请选择文件的原始坐标系');for(const k of ['point_id','name','lon','lat','coordinate_system','province','city','county','village_name','entrance_name','coordinate_source','verification_status','category','route_poi_type','official_batch','notes']){const field=$('#ti-'+k);if(!field)continue;const v=field.value;d.mapping[k]=v===''?null:Number(v)}el.disabled=true;try{const stats=await api(`/imports/${d.id}/validate`,'POST',{mapping:d.mapping,crs:d.crs});const issues=await api(`/datasets/${d.id}/points?issues=true&size=20`);d.stats=stats;d.issues=issues.rows;showTargetImport()}finally{el.disabled=false}},
 'target-import-back':()=>{targetImport.stats=null;showTargetImport()},
 'target-import-commit':async el=>{const d=targetImport;if(!d?.stats?.valid||d.importing)return;d.importing=true;el.disabled=true;try{await api(`/datasets/${d.id}/as-targets`,'POST');targetImport=null;$('#modal').close();await targetPage();toast(`已导入 ${d.stats.valid} 个目标，跳过 ${d.stats.invalid} 行异常数据`)}finally{d.importing=false;el.disabled=false}},
 'target-new':()=>targetForm(),'target-edit':el=>targetForm(targets.find(t=>t.id===+el.dataset.id)),
 'target-delete':async el=>{if(confirm('删除目标？已有任务的结果不受影响。')){await api('/targets/'+el.dataset.id,'DELETE');await targetPage()}},
 'target-save':async el=>{const error=$('#target-error');error.hidden=true;for(const [id,label,bound] of [['t-lon','经度',180],['t-lat','纬度',90]]){const input=$('#'+id),v=Number(input.value);if(input.value.trim()===''||!Number.isFinite(v)||Math.abs(v)>bound){error.textContent=label+'必须是 -'+bound+' 到 '+bound+' 之间的数字，请检查小数点。';error.hidden=false;input.focus();return}}if(!$('#t-name').value.trim()){error.textContent='名称不能为空。';error.hidden=false;$('#t-name').focus();return}await api('/targets'+(el.dataset.id?'/'+el.dataset.id:''),el.dataset.id?'PUT':'POST',{name:$('#t-name').value,lon:+$('#t-lon').value,lat:+$('#t-lat').value,crs:$('#t-crs').value,note:$('#t-note').value,target_id:$('#t-target-id').value,province:$('#t-province').value,city:$('#t-city').value,county:$('#t-county').value,village_name:$('#t-village').value,entrance_name:$('#t-entrance').value,coordinate_source:$('#t-coordinate-source').value,verification_status:$('#t-verification').value});$('#modal').close();await targetPage()},
 'save-settings':async()=>{settings=await api('/settings','PUT',{provider:$('#s-provider').value,qps:+$('#s-qps').value,max_concurrency:+$('#s-concurrency').value,daily_limit:+$('#s-limit').value,retries:+$('#s-retries').value,api_key:$('#s-key').value,plaintext:$('#s-plain').checked,strategy:'32'});wizard.provider=settings.provider;wizard.providerDefault=settings.provider;$('#provider-badge').textContent=settings.provider==='mock'?'模拟模式 · 仅供测试':'高德 · 当前路线估算';toast('设置已保存，新建任务将默认使用'+providerName(settings.provider));await settingsPage()}
};
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!actions[el.dataset.action])return;el.disabled=true;try{await actions[el.dataset.action](el)}catch(e){const box=$('#target-error');if(el.dataset.action==='target-save'&&box){box.textContent=e.message;box.hidden=false}else toast(e.message)}finally{if(el.isConnected)el.disabled=false}});
$('#exit').addEventListener('click',async()=>{if(confirm('退出应用？已完成结果保留，未完成任务下次可继续。')){try{await api('/shutdown','POST');$('#main').innerHTML=head('应用已退出','数据已保存在本机。再次双击应用即可继续。');view='closed'}catch(e){toast(e.message)}}});
document.addEventListener('change',e=>{if(e.target.id==='collection-mode'){wizard.collection_mode=e.target.value;const fields=$('#schedule-fields');if(fields)fields.hidden=e.target.value!=='scheduled';}});
window.addEventListener('hashchange',route);
async function poll(){try{if(view==='job'&&activeJob){const j=await api('/jobs/'+activeJob.id),changed=j.status!==activeJob.status;activeJob=j;if($('#job-progress'))$('#job-progress').innerHTML=progressHTML(j);if(changed&&$('#results'))await resultTable();if($('#research-report')&&(changed||(['queued','running','scheduled'].includes(j.status)&&Date.now()-lastReportRefresh>15000)))await showResearch()}if(view==='jobs'&&$('#job-list')){$('#job-list').innerHTML=jobTable(await api('/jobs'),true);updateSelectionControls()}}catch(e){}setTimeout(poll,2000)}
(async()=>{try{const version=await api('/version');if(version.version!=='2026.09.21.10')throw Error('应用版本已更新，请退出应用并重新打开');settings=await api('/settings');$('#provider-badge').textContent=settings.provider==='mock'?'模拟模式 · 仅供测试':'高德 · 当前路线估算';await route();poll()}catch(e){toast(e.message)}})();
