const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={};const context={console,URLSearchParams,document:{querySelector:s=>nodes[s]??=( {innerHTML:'',showModal(){},open:false}),querySelectorAll:()=>[]}};
vm.createContext(context);vm.runInContext(fs.readFileSync('frontend/app.js','utf8').split("document.addEventListener('click'")[0],context);
(async()=>{
 vm.runInContext(`api=async url=>url==='/settings'?{provider:'amap',qps:2}:url==='/targets'?[{id:1,name:'医院北门',category:'医院入口',institution_id:'H1'}]:url.startsWith('/source-nodes')?[{id:11,point_id:'O01',source_id:'O01',name:'来源甲',lon:114.3,lat:30.5,crs:'GCJ-02',population:1000,valid:1},{id:12,point_id:'O02',source_id:'O02',name:'来源乙',lon:112.9,lat:28.2,crs:'GCJ-02',population:2000,valid:1}]:url.endsWith('/categories')?[{category:'居民点',n:300}]:{points:300,entrances:30,institutions:20,routes_per_batch:9000,batches:1,total_routes:9000,planning_minutes:300,minimum_minutes:75,assumed_seconds:2,window_minutes:20,daily_requests:9000,local_daily_limit:1000,today_remaining:1000,max_attempts:36000,warnings:['预计超出窗口']};wizard={step:4,dataset_id:'D',stats:{valid:300},target_ids:[1]};`,context);
 await vm.runInContext('renderWizard()',context);assert(!nodes['#main'].innerHTML.includes('origin-category'));assert(!nodes['#main'].innerHTML.includes('select-target-category'));
 vm.runInContext("wizard.step=3;wizard.existing=true;wizard.source_point_ids=[]",context);await vm.runInContext('renderWizard()',context);assert(nodes['#main'].innerHTML.includes('选择本次要查询的客源地'));assert.equal((nodes['#main'].innerHTML.match(/class=\"source-check\"/g)||[]).length,2);
 vm.runInContext("wizard.step=6;wizard.mode='exact';wizard.candidates=5",context);await vm.runInContext('renderWizard()',context);assert(nodes['#main'].innerHTML.includes('estimate-seconds'));
 const plan=vm.runInContext('formalPlanRows()',context);assert.equal(plan.length,7);assert.equal(plan.reduce((n,row)=>n+row.times.length,0),7);assert.equal(plan.reduce((n,row)=>n+row.times.length*row.directions.length,0),7);assert.equal(JSON.stringify([...plan.map(row=>row.date)]),JSON.stringify(['2026-10-01','2026-10-02','2026-10-03','2026-10-17','2026-10-18','2026-10-24','2026-10-25']));assert(plan.every(row=>JSON.stringify(row.times)===JSON.stringify(['10:00'])));assert(plan.every(row=>JSON.stringify(row.directions)===JSON.stringify(['outbound'])));assert.equal(plan.find(row=>row.date==='2026-10-17').phase,'普通周末1·周六');
 vm.runInContext("wizard.step=5;wizard.collection_mode='scheduled';wizard.schedule=formalPlanRows();wizard.target_ids=[1,2];wizard.stats={valid:2};",context);await vm.runInContext('renderWizard()',context);assert(nodes['#main'].innerHTML.includes('2026年最终锁定研究计划：7天、7个时间轮、7个方向时间切片'));assert(nodes['#main'].innerHTML.includes('20,398'));assert(nodes['#main'].innerHTML.includes('一键填入7日最终锁定计划'));assert(nodes['#main'].innerHTML.includes('按当前选择预计'));assert(nodes['#main'].innerHTML.includes('方向'));assert(nodes['#main'].innerHTML.includes('窗口'));assert(nodes['#main'].innerHTML.includes('同一日期也可以设置多个不重叠时点'));assert(!nodes['#main'].innerHTML.includes('每个采集日只保留一行'));
 vm.runInContext("wizard.step=6;wizard.collection_mode='scheduled';wizard.schedule=formalPlanRows();wizard.directions=['outbound'];",context);await vm.runInContext('renderWizard()',context);assert(nodes['#main'].innerHTML.includes('采集方向已在上一页按日期设置'));assert(!nodes['#main'].innerHTML.includes('id=\"direction-outbound\"'));assert(nodes['#main'].innerHTML.includes('最终锁定方案仅查询去程'));
 vm.runInContext("wizard.step=7;wizard.times='08:00';wizard.collection_mode='immediate'",context);await vm.runInContext('renderWizard()',context);assert(nodes['#main'].innerHTML.includes('capacity-ack'));assert(nodes['#main'].innerHTML.includes('预计超出窗口'));
 vm.runInContext('targetForm({institution_id:"H1",category:"医院入口"})',context);assert(!nodes['#modal-body'].innerHTML.includes('t-institution_id'));
 console.log('Research UI rendering and warning controls passed');
})().catch(e=>{console.error(e);process.exit(1)});
